### ISSUE TITLE
Native Image Galleries

### ISSUE THREAD

**Issue by ys-chung** [redditbooru/reddit-booru#65]
Heads-up for the image search since [Reddit is adding native image galleries soon](https://www.reddit.com/r/modnews/comments/hisodw/image_gallery_support_is_coming_soon/).

**Comment by dxprog** [comment]
Thanks for the heads up. Wonder if it's just time to exit the image hosting business... reddit seems to have that covered and is serving their own copies of images most of the time, anyways.
